# Generated by Django 6.0 on 2025-12-11 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id_apoderado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_apoderado', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'apoderado',
            },
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id_ciclo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciclo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ciclo',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(blank=True, max_length=100, null=True)),
                ('horas_de_clase', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_docente', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='Simulacro',
            fields=[
                ('id_simulacro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_simulacro', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'simulacro',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tutor', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tutor',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena_usuario', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_educativo', models.CharField(blank=True, max_length=50, null=True)),
                ('id_apoderado', models.ForeignKey(db_column='id_apoderado', on_delete=django.db.models.deletion.CASCADE, to='myapp.apoderado')),
                ('id_tutor', models.ForeignKey(db_column='id_tutor', on_delete=django.db.models.deletion.CASCADE, to='myapp.tutor')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='CicloCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ciclo', models.ForeignKey(db_column='id_ciclo', on_delete=django.db.models.deletion.CASCADE, to='myapp.ciclo')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='myapp.curso')),
                ('id_docente', models.ForeignKey(blank=True, db_column='id_docente', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.docente')),
            ],
            options={
                'db_table': 'ciclo_curso',
                'unique_together': {('id_ciclo', 'id_curso')},
            },
        ),
        migrations.CreateModel(
            name='HorarioCurso',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(blank=True, max_length=15, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('id_ciclo_curso', models.ForeignKey(db_column='id_ciclo_curso', on_delete=django.db.models.deletion.CASCADE, to='myapp.ciclocurso')),
            ],
            options={
                'db_table': 'horario_curso',
            },
        ),
        migrations.AddField(
            model_name='ciclo',
            name='id_tutor',
            field=models.ForeignKey(blank=True, db_column='id_tutor', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tutor'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario'),
        ),
        migrations.AddField(
            model_name='docente',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado_asistencia', models.CharField(max_length=10)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='myapp.alumno')),
                ('id_ciclo', models.ForeignKey(db_column='id_ciclo', on_delete=django.db.models.deletion.CASCADE, to='myapp.ciclo')),
            ],
            options={
                'db_table': 'asistencia',
                'unique_together': {('id_alumno', 'id_ciclo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='AlumnoCicloCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='myapp.alumno')),
                ('id_ciclo', models.ForeignKey(db_column='id_ciclo', on_delete=django.db.models.deletion.CASCADE, to='myapp.ciclo')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='myapp.curso')),
            ],
            options={
                'db_table': 'alumno_ciclo_curso',
                'unique_together': {('id_alumno', 'id_ciclo', 'id_curso')},
            },
        ),
        migrations.CreateModel(
            name='SimulacroAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='myapp.alumno')),
                ('id_simulacro', models.ForeignKey(db_column='id_simulacro', on_delete=django.db.models.deletion.CASCADE, to='myapp.simulacro')),
            ],
            options={
                'db_table': 'simulacro_alumno',
                'unique_together': {('id_simulacro', 'id_alumno')},
            },
        ),
    ]
